// Jeux de flashcards pré-intégrés, regroupés par catégorie.
// Pour enrichir : ajoute des { q, a } dans une catégorie, ou une nouvelle clé de
// catégorie. L'ordre des clés = ordre d'affichage dans le sélecteur. Aucun réseau.
window.FLASHCARDS = {
  "Culture générale": [
    { q: "Qui a peint la Joconde ?", a: "Léonard de Vinci" },
    { q: "Qui a écrit « Les Misérables » ?", a: "Victor Hugo" },
    { q: "Qui a peint « La Nuit étoilée » ?", a: "Vincent van Gogh" },
    { q: "Qui a composé la « Neuvième Symphonie » ?", a: "Ludwig van Beethoven" },
    { q: "Combien de cordes a un violon ?", a: "Quatre" },
    { q: "Combien de cartes dans un jeu classique (sans jokers) ?", a: "52" },
    { q: "Combien de joueurs composent une équipe de football sur le terrain ?", a: "Onze" },
    { q: "Quelle est la monnaie du Royaume-Uni ?", a: "La livre sterling" },
    { q: "Quelle est la langue la plus parlée au monde (locuteurs natifs) ?", a: "Le mandarin" },
    { q: "Combien de couleurs distingue-t-on dans un arc-en-ciel ?", a: "Sept" },
    { q: "Quel est le plus petit nombre premier ?", a: "2" },
    { q: "De quel pays le tango est-il originaire ?", a: "L'Argentine" },
    { q: "Combien de notes compte la gamme musicale occidentale ?", a: "Sept (do, ré, mi, fa, sol, la, si)" },
    { q: "Qui a sculpté « Le Penseur » ?", a: "Auguste Rodin" },
    { q: "Quel écrivain a créé le personnage de Sherlock Holmes ?", a: "Arthur Conan Doyle" },
    { q: "Combien de touches compte un piano standard ?", a: "88" },
    { q: "Quel peintre espagnol a réalisé « Guernica » ?", a: "Pablo Picasso" },
    { q: "Combien de joueurs dans une équipe de basket sur le terrain ?", a: "Cinq" },
    { q: "Quel est le sport traditionnel emblématique du Japon ?", a: "Le sumo" },
    { q: "Quelle ville française accueille le festival du cinéma et sa Palme d'or ?", a: "Cannes" },
    { q: "Qui a écrit « Roméo et Juliette » ?", a: "William Shakespeare" },
    { q: "Combien de cases compte un échiquier ?", a: "64" },
    { q: "Quelle est la langue officielle du Brésil ?", a: "Le portugais" },
    { q: "Qui a peint le plafond de la chapelle Sixtine ?", a: "Michel-Ange" },
    { q: "Combien de faces a un dé classique ?", a: "Six" },
  ],
  "Histoire": [
    { q: "En quelle année a débuté la Révolution française ?", a: "1789" },
    { q: "Qui fut le premier empereur des Français ?", a: "Napoléon Ier" },
    { q: "En quelle année a pris fin la Seconde Guerre mondiale ?", a: "1945" },
    { q: "Quel mur est tombé en 1989 ?", a: "Le mur de Berlin" },
    { q: "Qui a atteint l'Amérique en 1492 ?", a: "Christophe Colomb" },
    { q: "En quelle année l'Homme a-t-il marché sur la Lune ?", a: "1969" },
    { q: "Quelle civilisation a construit les pyramides de Gizeh ?", a: "L'Égypte antique" },
    { q: "Quelle reine d'Égypte fut l'alliée de César puis d'Antoine ?", a: "Cléopâtre" },
    { q: "En quelle année a commencé la Première Guerre mondiale ?", a: "1914" },
    { q: "Quel roi de France est surnommé le « Roi-Soleil » ?", a: "Louis XIV" },
    { q: "Quelle révolution a éclaté en Russie en 1917 ?", a: "La révolution russe" },
    { q: "De quel empire Jules César fut-il une figure majeure ?", a: "L'Empire (la République) romain" },
    { q: "Quel général carthaginois a traversé les Alpes avec des éléphants ?", a: "Hannibal" },
    { q: "Quel événement, le 14 juillet 1789, symbolise le début de la Révolution ?", a: "La prise de la Bastille" },
    { q: "Qui dirigeait l'Allemagne nazie durant la Seconde Guerre mondiale ?", a: "Adolf Hitler" },
    { q: "En quelle année la Première Guerre mondiale s'est-elle terminée ?", a: "1918" },
    { q: "Quel navigateur a lancé la première expédition autour du monde ?", a: "Fernand de Magellan" },
    { q: "Quelle reine d'Angleterre a régné de 1558 à 1603 ?", a: "Élisabeth Ire" },
    { q: "Qui a fondé la Ve République française en 1958 ?", a: "Charles de Gaulle" },
    { q: "En quelle année la France a-t-elle aboli la peine de mort ?", a: "1981" },
    { q: "Quelle ville fut la capitale de l'Empire byzantin ?", a: "Constantinople" },
    { q: "Quelle bataille de 1815 marque la chute définitive de Napoléon ?", a: "Waterloo" },
    { q: "En quelle année ont eu lieu les attentats du 11 septembre ?", a: "2001" },
    { q: "Quel pharaon a un tombeau découvert quasi intact en 1922 ?", a: "Toutânkhamon" },
    { q: "Quelle guerre a opposé le Nord et le Sud des États-Unis (1861-1865) ?", a: "La guerre de Sécession" },
  ],
  "Géographie": [
    { q: "Quelle est la capitale de l'Australie ?", a: "Canberra" },
    { q: "Quel est le plus grand océan du monde ?", a: "L'océan Pacifique" },
    { q: "Quel est le plus haut sommet du monde ?", a: "L'Everest (8 849 m)" },
    { q: "Quel fleuve traverse Paris ?", a: "La Seine" },
    { q: "Quelle est la capitale du Japon ?", a: "Tokyo" },
    { q: "Quel est le plus grand désert chaud du monde ?", a: "Le Sahara" },
    { q: "Combien de continents y a-t-il ?", a: "Sept" },
    { q: "Quel pays a pour capitale Ottawa ?", a: "Le Canada" },
    { q: "Quel est le plus grand pays du monde par superficie ?", a: "La Russie" },
    { q: "Quelle mer sépare l'Europe de l'Afrique ?", a: "La mer Méditerranée" },
    { q: "Quelle est la capitale de l'Espagne ?", a: "Madrid" },
    { q: "Sur quel continent se trouve le Nil ?", a: "L'Afrique" },
    { q: "Quelle est la capitale de l'Allemagne ?", a: "Berlin" },
    { q: "Quel est le plus long fleuve d'Afrique ?", a: "Le Nil" },
    { q: "Quelle est la capitale des États-Unis ?", a: "Washington D.C." },
    { q: "Quel pays d'Amérique du Sud abrite la majeure partie de l'Amazonie ?", a: "Le Brésil" },
    { q: "Quel détroit sépare l'Espagne du Maroc ?", a: "Le détroit de Gibraltar" },
    { q: "Quelle est la plus grande île du monde ?", a: "Le Groenland" },
    { q: "Quelle chaîne de montagnes sépare la France de l'Espagne ?", a: "Les Pyrénées" },
    { q: "Quelle est la capitale de l'Égypte ?", a: "Le Caire" },
    { q: "Quel pays a une forme de botte ?", a: "L'Italie" },
    { q: "Quel est le plus grand lac d'Afrique ?", a: "Le lac Victoria" },
    { q: "Quelle est la capitale du Royaume-Uni ?", a: "Londres" },
    { q: "Quel pays compte le plus d'habitants au monde ?", a: "L'Inde" },
    { q: "Quelle est la capitale de la Grèce ?", a: "Athènes" },
  ],
  "Sciences": [
    { q: "Quelle est la planète la plus proche du Soleil ?", a: "Mercure" },
    { q: "Quelle est la plus grande planète du système solaire ?", a: "Jupiter" },
    { q: "Quel est le symbole chimique de l'or ?", a: "Au" },
    { q: "Quelle est la formule chimique de l'eau ?", a: "H₂O" },
    { q: "Quel gaz les plantes absorbent-elles pour la photosynthèse ?", a: "Le dioxyde de carbone (CO₂)" },
    { q: "Quelle est la vitesse de la lumière dans le vide (approx.) ?", a: "Environ 300 000 km/s" },
    { q: "Combien d'os compte le corps humain adulte ?", a: "206" },
    { q: "Qui a formulé la théorie de la relativité ?", a: "Albert Einstein" },
    { q: "Quel organe pompe le sang dans le corps ?", a: "Le cœur" },
    { q: "Quelle particule porte une charge négative ?", a: "L'électron" },
    { q: "Quel métal est liquide à température ambiante ?", a: "Le mercure" },
    { q: "Quel est l'élément chimique de symbole O ?", a: "L'oxygène" },
    { q: "Quel est le gaz le plus abondant dans l'atmosphère terrestre ?", a: "L'azote (le diazote)" },
    { q: "Combien de planètes compte le système solaire ?", a: "Huit" },
    { q: "Quel scientifique a énoncé la loi de la gravitation universelle ?", a: "Isaac Newton" },
    { q: "Quelle est l'unité de mesure de la force ?", a: "Le newton" },
    { q: "Quels organes assurent la respiration chez l'humain ?", a: "Les poumons" },
    { q: "Quelle molécule porte l'information génétique ?", a: "L'ADN" },
    { q: "Quel est le symbole chimique du fer ?", a: "Fe" },
    { q: "Quelle force attire les objets vers le sol ?", a: "La gravité (la pesanteur)" },
    { q: "Quelle planète est surnommée « la planète rouge » ?", a: "Mars" },
    { q: "Combien de chromosomes possède l'être humain ?", a: "46 (23 paires)" },
    { q: "Quel instrument mesure la température ?", a: "Le thermomètre" },
    { q: "Quel astre se trouve au centre du système solaire ?", a: "Le Soleil" },
    { q: "Quelle est l'unité de base du vivant ?", a: "La cellule" },
  ],
};
