// Jeux de flashcards pré-intégrés, regroupés par catégorie.
// Pour enrichir : ajoute des { q, a } dans une catégorie, ou une nouvelle clé de
// catégorie. L'ordre des clés = ordre d'affichage dans le sélecteur. Aucun réseau.
window.FLASHCARDS = {
  "Culture générale": [
    { q: "Qui a peint la Joconde ?", a: "Léonard de Vinci" },
    { q: "Qui a écrit « Les Misérables » ?", a: "Victor Hugo" },
    { q: "Qui a peint « La Nuit étoilée » ?", a: "Vincent van Gogh" },
    { q: "Qui a composé la « Neuvième Symphonie » ?", a: "Ludwig van Beethoven" },
    { q: "Combien de cordes a un violon ?", a: "Quatre" },
    { q: "Combien de cartes dans un jeu classique (sans jokers) ?", a: "52" },
    { q: "Combien de joueurs composent une équipe de football sur le terrain ?", a: "Onze" },
    { q: "Quelle est la monnaie du Royaume-Uni ?", a: "La livre sterling" },
    { q: "Quelle est la langue la plus parlée au monde (locuteurs natifs) ?", a: "Le mandarin" },
    { q: "Combien de couleurs distingue-t-on dans un arc-en-ciel ?", a: "Sept" },
    { q: "Quel est le plus petit nombre premier ?", a: "2" },
    { q: "De quel pays le tango est-il originaire ?", a: "L'Argentine" },
  ],
  "Histoire": [
    { q: "En quelle année a débuté la Révolution française ?", a: "1789" },
    { q: "Qui fut le premier empereur des Français ?", a: "Napoléon Ier" },
    { q: "En quelle année a pris fin la Seconde Guerre mondiale ?", a: "1945" },
    { q: "Quel mur est tombé en 1989 ?", a: "Le mur de Berlin" },
    { q: "Qui a atteint l'Amérique en 1492 ?", a: "Christophe Colomb" },
    { q: "En quelle année l'Homme a-t-il marché sur la Lune ?", a: "1969" },
    { q: "Quelle civilisation a construit les pyramides de Gizeh ?", a: "L'Égypte antique" },
    { q: "Quelle reine d'Égypte fut l'alliée de César puis d'Antoine ?", a: "Cléopâtre" },
    { q: "En quelle année a commencé la Première Guerre mondiale ?", a: "1914" },
    { q: "Quel roi de France est surnommé le « Roi-Soleil » ?", a: "Louis XIV" },
    { q: "Quelle révolution a éclaté en Russie en 1917 ?", a: "La révolution russe" },
    { q: "Quel empire fut dirigé par Jules César ?", a: "L'Empire (la République) romain" },
  ],
  "Géographie": [
    { q: "Quelle est la capitale de l'Australie ?", a: "Canberra" },
    { q: "Quel est le plus grand océan du monde ?", a: "L'océan Pacifique" },
    { q: "Quel est le plus haut sommet du monde ?", a: "L'Everest (8 849 m)" },
    { q: "Quel fleuve traverse Paris ?", a: "La Seine" },
    { q: "Quelle est la capitale du Japon ?", a: "Tokyo" },
    { q: "Quel est le plus grand désert chaud du monde ?", a: "Le Sahara" },
    { q: "Combien de continents y a-t-il ?", a: "Sept" },
    { q: "Quel pays a pour capitale Ottawa ?", a: "Le Canada" },
    { q: "Quel est le plus grand pays du monde par superficie ?", a: "La Russie" },
    { q: "Quelle mer sépare l'Europe de l'Afrique ?", a: "La mer Méditerranée" },
    { q: "Quelle est la capitale de l'Espagne ?", a: "Madrid" },
    { q: "Sur quel continent se trouve le Nil ?", a: "L'Afrique" },
  ],
  "Sciences": [
    { q: "Quelle est la planète la plus proche du Soleil ?", a: "Mercure" },
    { q: "Quelle est la plus grande planète du système solaire ?", a: "Jupiter" },
    { q: "Quel est le symbole chimique de l'or ?", a: "Au" },
    { q: "Quelle est la formule chimique de l'eau ?", a: "H₂O" },
    { q: "Quel gaz les plantes absorbent-elles pour la photosynthèse ?", a: "Le dioxyde de carbone (CO₂)" },
    { q: "Quelle est la vitesse de la lumière dans le vide (approx.) ?", a: "Environ 300 000 km/s" },
    { q: "Combien d'os compte le corps humain adulte ?", a: "206" },
    { q: "Qui a formulé la théorie de la relativité ?", a: "Albert Einstein" },
    { q: "Quel organe pompe le sang dans le corps ?", a: "Le cœur" },
    { q: "Quelle particule porte une charge négative ?", a: "L'électron" },
    { q: "Quel métal est liquide à température ambiante ?", a: "Le mercure" },
    { q: "Quel est l'élément chimique de symbole O ?", a: "L'oxygène" },
  ],
};
